config/routes.rb
Rails.application.routes.draw do

  get 'evaluation_employee/new'
  resources :evaluation_employee
  namespace :admins_backoffice do
    get 'welcome/index' ##Dashbooard
    resources :admins
    resources :employees

  end
  
  devise_for :admins do
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end

  get 'employee/:id', to: 'evaluation_employee#show_modal', as: :show_modal
  
  get 'admin', to: 'admins_backoffice/welcome#index'
  root to: 'evaluation_employee#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :evaluation_employees, dependent: :delete_all

    mount_uploader :avatar, AvatarUploader
    
    validates :name, presence: true, length: { minimum: 3 }
    validates :office, presence: true   
end

app/models/evaluation_company.rb
class EvaluationCompany < ApplicationRecord
    belongs_to :employee
end

app/models/evaluation_employee.rb
class EvaluationEmployee < ApplicationRecord
  belongs_to :employee
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
    def index
        @admins = Admin.all
    end
end

app/controllers/admins_backoffice/employees_controller.rb
class AdminsBackoffice::EmployeesController < AdminsBackofficeController
    before_action :set_employee, only: [:show, :edit, :update, :destroy, :show_modal]

    def index
        @employees = Employee.all
    end

    def new
        @employee = Employee.new
    end 

    def show
    end

    def edit
    end

    def update
        if @employee.update(employee_params)
          redirect_to admins_backoffice_employees_path, notice: "Colaborador atualizado com sucesso"
        else 
          render :edit
        end
    end

    def create
        @employee = Employee.new(employee_params)
        if @employee.save
          redirect_to admins_backoffice_employees_path, notice: "Colaborador Salvo com sucesso!"
        else 
          render :new
        end
    end 

    def destroy
        if @employee.destroy
          redirect_to admins_backoffice_employees_path, notice: "Colaborador excluído com sucesso"
        else 
          render :index 
        end
    end

    private 

        def set_employee
            @employee = Employee.find(params[:id])
        end 

        def employee_params
            params.require(:employee).permit(:name, :office, :avatar)
        end 
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
    def index
        @employee = Employee.all
        @evaluation = EvaluationEmployee.all
    end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    ##Protegendo páginas internas
    before_action :authenticate_admin!
    layout 'admin_backoffice'

    def after_sign_in_path_for(resource)
        admins_backoffice_welcome_index_path(current_admin) #your path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/evaluation_employee_controller.rb
class EvaluationEmployeeController < ApplicationController  
  before_action :set_employee, only: [:show_modal]
  skip_before_action :verify_authenticity_token

  def index
    @employees = Employee.all
  end

  def create
    @evaluationEmployee = EvaluationEmployee.new(set_params)
    if @evaluationEmployee.save
      redirect_to root_path, notice: "Colaborador Salvo com sucesso!"
    else 
      flash[:error] = "falha ao salvar a avaliação"
      redirect_to root_path
    end
  end

  def show_modal
    @evaluationEmployee = EvaluationEmployee.new
    respond_to do |format|
      format.html {render :partial => "show_modal"}
      format.js
    end 
  end 

  private 
      def set_employee
        @employee = Employee.find(params[:id])
      end 

      def set_params
        params.require(:evaluation_employee).permit(:grades, :comments, :employee_id)
      end 
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/employees_helper.rb
module AdminsBackoffice::EmployeesHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def evaluation_positive
        @positive_evaluations = EvaluationEmployee.where("grades > 6")
        return @positive_evaluations.size
    end 

    def evaluation_negative
        @negative_evaluations = EvaluationEmployee.where("grades < 6")
        return @negative_evaluations.size
    end 
end

app/helpers/evaluation_employee_helper.rb
module EvaluationEmployeeHelper
end

app/views/admins_backoffice/admins/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Administradores</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<%= link_to new_admins_backoffice_admin_path, :class => "btn btn-success" do %>
    <i class="fa fa-plus"></i> Novo Administrador
<% end %>
<br></br>

<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Email</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <% @admins.each do |admin| %>
                <tr>
                    <td><%= admin.id %></td>
                    <td><%= admin.email %></td>
                    <td style="width:100px;">
                        <%= link_to edit_admins_backoffice_admin_path(admin), :class => "btn btn-primary btn-circle" do %>
                            <i class="fa fa-edit"></i>
                        <% end %>

                        <%= link_to admins_backoffice_admin_path(admin), method: :delete, :class => "btn btn-danger btn-circle",  data: { confirm: "Deseja realmente excluír administrador" } do %>
                            <i class="fa fa-trash"></i>
                        <% end %>

                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admins_backoffice/employees/edit.html.erb
<%= render partial: 'admins_backoffice/employees/shared/form',
 locals: { action_message: 'Editar Colaborador' } %>

app/views/admins_backoffice/employees/index.html.erb
<div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
        <div class="x_title">
        <h2>Colaboradores</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li>
                <%= link_to new_admins_backoffice_employee_path do %>
                    <i class="fa fa-plus"></i>
                <% end %>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
        </ul>
        <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="row">
                <div class="col-sm-12">
                <div class="card-box table-responsive">

        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Cargo</th>
                <th>Total de Avaliações</th>
                <th>Total Avaliaçoes Positivas</th>
                <th>Total Avaliações Negativas</th>
                <th>Total Comentários</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <% @employees.each do |employee|%>
                <tr>
                    <td><%= employee.name %> </td>
                    <td><%= employee.office %></td>
                    <td><%= employee.evaluation_employees.size %></td>
                    <td><%= employee.evaluation_employees.where("grades > 6").size %></td>
                    <td><%= employee.evaluation_employees.where("grades < 6").size %></td>
                    <td><%= employee.evaluation_employees.size %></td>
                    <td>
                        <%= link_to edit_admins_backoffice_employee_path(employee) do %>
                            <i class="fa fa-edit"></i>
                        <% end %>
                        <%= link_to admins_backoffice_employee_path(employee), method: :delete, data: { confirm: "Deseja realmente excluír colaborador" } do %>
                            <i class="fa fa-trash"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
        </div>
    </div>
</div>

app/views/admins_backoffice/employees/new.html.erb
<%= render partial: 'admins_backoffice/employees/shared/form', locals: { action_message: 'Cadastrar Colaborador' } %>

app/views/admins_backoffice/employees/shared/_form.html.erb
<div role="main">
    <div class="clearfix"></div>
    <div class="row">

        <% if @employee.errors.any? %>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert"
                aria-hidden="true">×</button>
                <ul>
                    <% @employee.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><%= action_message %></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <%= form_with(model: [ :admins_backoffice, @employee  ], local: true, class:"form-horizontal form-label-left") do |form|  %>
                        <div class="item form-group">
                            <%= form.label :name, :class => "col-form-label col-md-3 col-sm-3 label-align"%>
                            <div class="col-md-6 col-sm-6">
                                <%= form.text_field :name, :class => "form-control", :placeholder => "Nome Completo" %>
                            </div>
                        </div>   
                        <div class="item form-group">
                            <%= form.label :office, :class => "col-form-label col-md-3 col-sm-3 label-align"%>
                            <div class="col-md-6 col-sm-6">
                                <%= form.text_field :office, :class => "form-control", :placeholder => "Cargo" %>
                            </div>
                        </div>   
                        <div class="item form-group">
                            <div class="col-md-6 col-sm-6" style="margin: 0 auto">                        
                                <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="fa fa-picture-o"></i></a>
                                <%= form.file_field :avatar, :"data-role"=> "magic-overlay", :"data-target" => "#pictureBtn", :"data-edit" => "insertImage" %>
                                <!--<input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" name="employee[avatar]" id="employee_avatar" />        -->           
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="item form-group">
                            <div class="col-md-6 col-sm-6 offset-md-3">
                                <button type="submit" class="btn btn-success">Salvar</button>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admins_backoffice/welcome/index.html.erb
    <!-- top tiles -->
<div class="row" style="display: inline-block;" >
    <div class="tile_count">
    <div class="col-md-2 col-sm-4  tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total de Colaboradores</span>
        <div class="count"><%= @employee.size %></div>
    </div>
    <div class="col-md-2 col-sm-4  tile_stats_count">
        <span class="count_top"><i class="fa fa-clock-o"></i>Total de Avaliações</span>
        <div class="count"><%= @evaluation.size %></div>
    </div>
    <div class="col-md-2 col-sm-4  tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total Avaliações positivas</span>
        <div class="count green"><%= evaluation_positive %></div>
    </div>
    <div class="col-md-2 col-sm-4  tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i>Total Avaliações Negativas</span>
        <div class="count red"><%= evaluation_negative %></div>
    </div>
    <div class="col-md-2 col-sm-4  tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total de comentários</span>
        <div class="count"><%= @evaluation.size %></div>
    </div>
</div>

app/views/evaluation/index.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Avalie nossos Colaboradores</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Ajude-nos a melhorar cada vez mais nosso atendimento
                </div>
                <div class="panel-body">
                    <div class="row" style="display:flex">
                        <% @employees.each do |employee| %>
                            <div class="card" style="max-width: 20rem; padding:16px; margin:24px; border:3px solid #f0f0f0;">
                                <% if employee.avatar.blank? %>
                                    <img class="card-img-top" src="/templates/gentelella/production/images/img.jpg" alt="Card image cap">
                                <% else %>
                                    <img class="card-img-top" src="<%= employee.avatar %>" alt="Card image cap" style="width:100%;max-width:130px;height:130px;object-fit:cover;">
                                <% end %>
                                <div class="card-body">
                                    <h5 class="card-title"><%= employee.name %></h5>
                                    <p class="card-text"><%= employee.office %></p>
                                    <a href="#" class="btn btn-primary">Avaliar</a>
                                </div>
                            </div>
                        <% end %>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>

app/views/evaluation_employee/_show_modal.html.erb
<% if @evaluationEmployee.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert"
        aria-hidden="true">×</button>
        <ul>
            <% @evaluationEmployee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<div class="modal-header">
  <h4 class="modal-title" id="evaluationEmployeeLabel">
      Avalie <strong><%= @employee.name %></strong>
  </h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<form action="/evaluation_employee" method="post" accept-charset="UTF-8" >
<div class="modal-body">
  <form>
    <div class="form-group">
      <label for="evaluation_employee[grades]">Nota para atendimento</label>
      <input type="number" id="replyNumber" min="0" max="10" class="form-control" name="evaluation_employee[grades]" id="evaluation_employee[grades]"  placeholder="Digite uma nota">
    </div>
    <div class="form-group">
      <label for="evaluation_employee[comments]">Comentário</label>
      <textarea type="text-area" class="form-control" name="evaluation_employee[comments]" id="evaluation_employee[comments]"  rows="3" placeholder="Deixe um comentário para melhorarmos no nosso atendimento"></textarea>
    </div>
    <input type="hidden" value="<%= @employee.id%>" name="evaluation_employee[employee_id]" id="evaluation_employee[employee_id]">
</div>
<br/>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
  <button type="submit" class="btn btn-primary">Avaliar</button>
</div>
</form>

app/views/evaluation_employee/create.html.erb
<h1>Evaluation#create</h1>
<p>Find me in app/views/evaluation/create.html.erb</p>

app/views/evaluation_employee/index.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Avalie nossos Colaboradores</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Ajude-nos a melhorar cada vez mais nosso atendimento
                </div>
                <div class="panel-body">
                    <div class="row" style="display:flex">
                        <% @employees.each do |employee| %>
                            <div class="card" style="max-width: 20rem; padding:16px; margin:24px; border:3px solid #f0f0f0;">
                                <% if employee.avatar.blank? %>
                                    <img class="card-img-top" src="/templates/gentelella/production/images/img.jpg" alt="Card image cap">
                                <% else %>
                                    <img class="card-img-top" src="<%= employee.avatar %>" alt="Card image cap" style="width:100%;max-width:130px;height:130px;object-fit:cover;">
                                <% end %>
                                <div class="card-body">
                                    <h5 class="card-title"><%= employee.name %></h5>
                                    <p class="card-text"><%= employee.office %></p>
                                    <%= link_to 'Avaliar', show_modal_path(employee), :remote => true, :class => "btn btn-primary", 'data-toogle' => "modal", 'data-target' => "#evaluationEmployee" %>
                                </div>
                            </div>
                        <% end %>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>

<!-- MODAL -->
<div class="modal fade" id="evaluationEmployee" tabindex="-1" role="dialog" aria-labelledby="evaluationEmployeeLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- jQuery -->
<script src="/templates/startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/templates/startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/templates/startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/templates/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js"></script>

<!-- Page-Level Demo Scripts - Notifications - Use for reference -->
<script>
// tooltip demo
$('.tooltip-demo').tooltip({
    selector: "[data-toggle=tooltip]",
    container: "body"
})
// popover demo
$("[data-toggle=popover]")
    .popover()
</script>

app/views/evaluation_employee/show_modal.js.erb
$("#evaluationEmployee").find(".modal-content").html("<%= j (render 'show_modal') %>");
$("#evaluationEmployee").modal();

app/views/layouts/admin_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Avaliação</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>

    <!-- Bootstrap -->
    <link href="/templates/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/templates/gentelella/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/templates/gentelella/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="/templates/gentelella/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>

    <!-- Custom Theme Style -->
    <link href="/templates/gentelella/build/css/custom.min.css" rel="stylesheet">
  </head>
  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Painel Administrador</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <%#= link_to image_tag(avatar_url, alt:"...", class:"img-circle profile_img"), "#", "data-toggle":"modal", "data-target":"#avatarModal" %>
              </div>
              <div class="profile_info">
                <span>Seja Bem vindo,</span>
                <h2><%= current_admin.email %></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Geral</h3>
                <ul class="nav side-menu">  
                  <li>
                    <%= link_to admins_backoffice_welcome_index_path	do %> 
                      <i class="fa fa-home"></i> Início
                    <% end %>    
                  </li>       
                  <li>
                    <%= link_to admins_backoffice_employees_path do %>
                      <i class="fa fa-user"></i> Colaboradores
                    <% end %>
                  </li>    
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                  <li class="nav-item dropdown open" style="padding-left: 15px;">
                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                      <%#= image_tag avatar_url, alt:"..." %>
                      <%= current_admin.first_name %>
                    </a>
                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item"  href="javascript:;"> Profile</a>
                        <a class="dropdown-item"  href="javascript:;">
                          <span class="badge bg-red pull-right">50%</span>
                          <span>Settings</span>
                        </a>
                      <a class="dropdown-item"  href="javascript:;">Help</a>
                      <%= link_to destroy_admin_session_path, method: :get, :class => "dropdown-item"  do %>
                        <i class="fa fa-sign-out pull-right"></i> Log Out
                      <% end %>
                    </div>
                  </li>
  
                  <li role="presentation" class="nav-item dropdown open">
                    <a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1" data-toggle="dropdown" aria-expanded="false">
                      <i class="fa fa-envelope-o"></i>
                      <span class="badge bg-green">0</span>
                    </a>
                    <ul class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbarDropdown1">
                      <li class="nav-item">
                        <a class="dropdown-item">
                          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                          <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                          <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="dropdown-item">
                          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                          <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                          <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="dropdown-item">
                          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                          <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                          <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="dropdown-item">
                          <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                          <span>
                            <span>John Smith</span>
                            <span class="time">3 mins ago</span>
                          </span>
                          <span class="message">
                            Film festivals used to be do-or-die moments for movie makers. They were where...
                          </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <div class="text-center">
                          <a class="dropdown-item">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                          </a>
                        </div>
                      </li>
                    </ul>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <%= yield %>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->

        <!-- /footer content -->
      </div>
    </div>


    <%= javascript_pack_tag 'application' %>
    <!-- jQuery -->
    <script src="/templates/gentelella/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
   <script src="/templates/gentelella/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- FastClick -->
    <script src="/templates/gentelella/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/templates/gentelella/vendors/nprogress/nprogress.js"></script>
    <!-- jQuery custom content scroller -->
    <script src="/templates/gentelella/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="/js/jquery.bootstrap-growl.min.js"></script>

    <% if notice %>
        <%= javascript_tag do %>
            $.bootstrapGrowl("<%= notice %>", {
                type: 'success', // (null, 'info', 'danger', 'success')
                align: 'right', // ('left', 'right', or 'center')
                allow_dismiss: true, // If true then will display a cross to close the popup.
                stackup_spacing: 10 // spacing between consecutively stacked growls.
            });     
        <% end %>
    <% end %>

    <!-- Custom Theme Scripts -->
    <script src="/templates/gentelella/build/js/custom.min.js"></script>
  </body>
</html>